### ISSUE TITLE
Error when selecting file

### ISSUE THREAD

**Issue by davidbonachera** [cstefanache/angular2-img-cropper#12] opened 2016-06-13 01:29 UTC
I have this error when i select a file on my html page.

`zone.js:260 Uncaught EXCEPTION: Error in ./ImageCropperComponent class ImageCropperComponent - inline template:2:25
ORIGINAL EXCEPTION: RangeError: Maximum call stack size exceeded
ORIGINAL STACKTRACE:

browser_adapter.js:77 RangeError: Maximum call stack size exceeded
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
    at get (zone.js:966)
`
Don't understand where it comes from. I use ZoneJs but i don't see where the loop on get come from.

**Comment by cstefanache** [comment] 2016-06-13 06:16
Hello,

I do not seem to find where the issue is triggered.
here is a working plunker: https://embed.plnkr.co/V91mKCNkBQZB5QO2MUP4/

**Comment by davidbonachera** [comment] 2016-06-13 09:40
Hum weird,it may be a problem related to the angular2-meteor-bootstrap wrapper i'm using so, because i have the same setup as your plunkr. I'm looking into this.

**Comment by cstefanache** [comment] 2016-06-13 14:14
If you can reproduce it on a plnkr fork I can have a look into it

**Comment by Mihai-B** [comment] 2016-06-14 21:57
what version of angular are you using?
And what version of zone.js are you using?

**Comment by davidbonachera** [comment] 2016-06-24 06:37
This is my package.json, i'll try to post a plunkr this week-end.
```javascript
{
  "name": "beacon-cms",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.1",
    "@angular/compiler": "^2.0.0-rc.1",
    "@angular/core": "^2.0.0-rc.1",
    "@angular/http": "^2.0.0-rc.1",
    "@angular/platform-browser": "^2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.1",
    "angular2-fontawesome": ">=0.3.0",
    "angular2-google-maps": "^0.10.0",
    "angular2-locker": "^0.3.0",
    "angular2-meteor": "^0.5.5",
    "angular2-meteor-accounts-ui": "^0.4.3",
    "angular2-meteor-auto-bootstrap": "^0.5.5",
    "bootstrap": "^4.0.0-alpha.2",
    "es6-shim": "^0.35.1",
    "h5webstorage": "^0.4.2",
    "jquery": "^2.2.4",
    "meteor-node-stubs": "^0.2.3",
    "ng2-bootstrap": "^1.0.17",
    "ng2-datetime": "^1.0.3",
    "reflect-metadata": "^0.1.2",
    "rxjs": "^5.0.0-beta.6",
    "tether": "^1.3.2",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "codelyzer": "0.0.19"
  }
}
```

**Comment by cstefanache** [comment] 2016-06-24 06:45
How do you load angular/cropper files? 
Do you use system.js or bundle in a single file?
Can you paste system.config file content?

**Comment by davidbonachera** [comment] 2016-06-24 06:48
I use commonjs.

This is my tsconfig.json : 
```javascript
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": true,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "client/**/*.ts",
    "server/**/*.ts",
    "typings/**/*.d.ts"
  ]
}
```

**Comment by davidbonachera** [comment] 2016-06-28 03:46
After some upgrades of my core and using the new angular router the problem is solved. It came from the compatibility between my meteor packages and my angular application.

**Comment by cstefanache** [comment] 2016-06-28 04:45
Awesome! Closing issue...

**Closed by cstefanache** 2016-06-28 04:45 UTC
Labels: bug
