### ISSUE TITLE
ImageCropperComponent and AOT

### ISSUE THREAD

**Issue by andershagebakken** [cstefanache/angular2-img-cropper#95] opened 2016-11-19 10:53 UTC
Hi. Great work on the cropper. 

I just have a question. I am using angular-cli, and when I am trying to run `ng build --prod --aot` I get the following error:

Type ImageCropperComponent is part of the declarations of 2 modules: ImageCropperModule and AppModule! Please consider moving ImageCropperComponent to a higher module that imports ImageCropperModule and AppModule. You can also create a new NgModule that exports and includes ImageCropperComponent then import that NgModule in ImageCropperModule and AppModule.

It works very well without the aot-flag, so is there any way to solve this? Thanks. :-)

**Comment by cstefanache** [comment] 2016-12-11 02:22
Duplicate of #89 - closing for now and leaving that thread open - will try to fix for 0.8

**Comment by fractsa** [comment] 2017-03-09 14:47
Seems not fixed yet in 0.8 ? any chance to get it fixed ?
Thanks a lot, this cropper is great !

**Comment by akigrafsoft** [comment] 2017-03-09 14:49
Hi, thanks for this excellent cropper.
The issue here does not seem to be fixed in 0.8, I still get the same.
Any chance to get it fixed ?
Thanks a lot !

**Comment by cstefanache** [comment] 2017-03-09 15:10
can this be closed?

**Comment by akigrafsoft** [comment] 2017-03-09 15:10
Yes you can closed it now ;) sorry for the noise !

**Comment by cstefanache** [comment] 2017-03-09 15:11
thanks! no worries

**Closed by cstefanache** 2017-03-09 15:11 UTC
Labels: help wanted

**Comment by vegaskev** [comment] 2017-08-03 07:39
Just to confirm for anyone else visiting this issue thread that the solution/explanation provided by @andershagebakken works 100%.  [Click to scroll to the comment.](https://github.com/cstefanache/angular2-img-cropper/issues/95#issuecomment-285371570)

**Comment by genyklemberg** [comment] 2018-02-19 08:19
@cstefanache Can you just provide the right code for module and component so `ng build --prod ` would work properly? As I saw in your img-cropper docs https://github.com/cstefanache/angular2-img-cropper we can't use declarations in Component. It's really confusing to see all different answers all over github and stackoverflow. Thanks for your efforts.

**Comment by web-dave** [comment] 2018-02-19 08:41
This repo is deprecated.

use this one for any further issues and please make noise to let the world know about that new name.
https://github.com/web-dave/ngx-img-cropper

**Comment by web-dave** [comment] 2018-02-19 08:45
here is my showcase wich works with ng build --prod
https://github.com/web-dave/ngx-img-cropper-showcase
