### ISSUE TITLE
index.js "not transpiling" in last version

### ISSUE THREAD

**Issue by littletime** [cstefanache/angular2-img-cropper#179] opened 2017-04-11 10:46 UTC
Hi,

After updating to version 0.8.6, I'm having the error : 
`Error loading http://localhost:3000/typescript
Unable to load transpiler to transpile http://localhost:3000/node_modules/ng2-img-cropper/index.js`

Maybe I'm missing something on how TypeScript works since it's pretty new to me but it looks like the index.js in the last version of the NPM package is actually written in TypeScript. 

This is my index.js file : 

`// core
export { ImageCropperModule } from './src/imageCropperModule';
export { ImageCropperComponent } from './src/imageCropperComponent';
// extra classes
export { ImageCropper } from './src/imageCropper';
export { CropperSettings } from './src/cropperSettings';
export { CropperDrawSettings } from './src/cropperDrawSettings';
// models
export { Bounds } from './src/model/bounds';
export { CropPosition } from './src/model/cropPosition';
//# sourceMappingURL=index.js.map`

When the same file in previous version looked a lot more like JS. Maybe there was an error in pushing the version ?

**Comment by cstefanache** [comment] 2017-04-20 04:38
duplicate of #175

**Closed by cstefanache** 2017-04-20 04:38 UTC
