### ISSUE TITLE
File Input Button Layout/Position

### ISSUE THREAD

**Issue by mattes42** [cstefanache/angular2-img-cropper#26] opened 2016-07-07 13:16 UTC
As of v0.4.5 the cropper made a huge step forward regarding customization. Thumbs up!

Nevertheless on more idea on customization. Do you have a suggestion of how to position the file input button freely? The template for the ImageCropperComponent has a fixed order of button and canvas. It would be great if there was a separate directive for the button, just like in Allan Bishop's ng1 cropper. That way you could put the button anywhere on the screen, and put similar buttons right next to it, like "remove image".

**Comment by cstefanache** [comment] 2016-07-07 13:34
This is a duplicate of [Issue 23](https://github.com/cstefanache/angular2-img-cropper/issues/23) - Still it will be kept as unclosed and milestone set to 0.5. Keeping unclosed for more suggestions

**Comment by mattes42** [comment] 2016-07-07 13:52
Isn't #23 about styling the file input button? I thought of positioning it. Consider this example, where one could require to place the input button somewhere else. I introduced the dummy directive "img-cropper-fileinput" as a placeholder for the file input button. The img-cropper directive would render only the canvas.

`<div class="croppercanvas">`
`<img-cropper ...>  </img-cropper>`
 `</div>`
`  ....`
`<div class="myactionbuttons">`
 `  <img-cropper-fileinput></img-cropper-fileinput>`
 ` <button> Delete Image </button>`
`</div>`


In the current implementation the file input button would be stuck next to the canvas. Or am I missing something?

**Comment by cstefanache** [comment] 2016-07-07 15:02
You are absolutely correct. 
This is the reason why I did not closed the issue (but marked it as duplicate - so I can have the refference) - your example extends issue no. 23 functionality. At one coment there is a suggestion to use transclusion. 

I am planning to finish this over weekend.

**Comment by cstefanache** [comment] 2016-07-11 11:15
Hello,

I managed to update the code in order to support external input button. This is the result (ignore the styling - just wanted to make it fancy)

![image](https://cloud.githubusercontent.com/assets/3071201/16728872/ab4679da-4771-11e6-98f5-c8765f5eeb11.png)

I have added noFileInput attribute to cropperSettings object in order to hide the img cropper component internal file input. I will push and update the documentation asap

**Closed** 2016-07-11 18:03 UTC
Labels: duplicate, enhancement, in reivew
